http:
  port: 5005
  health_check_path: /
name: Pristine GitHub Issue Manager
summary: An AI agent named Pristine that manages issues on a GitHub repository by creating, updating, and closing issues, detecting TODOs, suggesting features, and prioritizing tasks.
environment_variables:
  - name: OPENAI_API_KEY
    value: <your_openai_api_key>
    description: The API key for authenticating with the OpenAI API.
  - name: OPENAI_API_BASE
    value: https://api.openai.com
    description: The base URL for the OpenAI API. Defaults to https://api.openai.com.
  - name: OPENAI_API_MODEL
    value: gpt-3.5-turbo
    description: The name of the OpenAI model to use for LLM inference. Defaults to gpt-3.5-turbo.
  - name: GITHUB_REPOSITORY_OWNER
    value: <github_repo_owner>
    description: The GitHub username or organization that owns the target repository.
  - name: GITHUB_REPOSITORY_NAME
    value: <github_repo_name>
    description: The name of the GitHub repository the agent will manage.
  - name: GITHUB_REPOSITORY_ISSUES_BRANCH
    value: issues
    description: The name of the Git branch where issues are managed. Defaults to 'issues'.