http:
  port: 5005 # Port on which the agent's HTTP server listens
  health_check_path: / # Path for health checks
name: Pristine Agent
summary: An AI agent that manages GitHub issues by detecting bugs, missing documentation, and tests, and interacting with LLMs to create, update, and close issues. It also provides a web dashboard for monitoring.
environment_variables:
  - name: GITHUB_PERSONAL_ACCESS_TOKEN
    value: <your_github_personal_access_token>
    description: A GitHub personal access token with permissions to clone repositories and manage issues (read/write issues, pull requests, and repository contents).
  - name: OPENAI_API_KEY
    value: <your_openai_api_key>
    description: The OpenAI API key used for large language model inference.
  - name: OPENAI_API_BASE
    value: https://api.openai.com
    description: The base URL for the OpenAI API. Defaults to https://api.openai.com.
  - name: OPENAI_API_MODEL
    value: gpt-3.5-turbo
    description: The specific OpenAI LLM model to use for text generation. Defaults to gpt-3.5-turbo.
  - name: GITHUB_REPOSITORY_OWNER
    value: <github_repository_owner>
    description: The GitHub username or organization name that owns the target repository the agent will manage.
  - name: GITHUB_REPOSITORY_NAME
    value: <github_repository_name>
    description: The name of the GitHub repository the agent will interact with.
  - name: GITHUB_REPOSITORY_ISSUES_BRANCH
    value: issues
    description: The Git branch where the agent will manage issues. Defaults to 'issues'.